# Change these first
repo: thalatta  # The name of this repository
owner: AvgGeo
sites:
  - name: Thalatta-Thalatta.com
    url: https://thalatta-thalatta.com
  - name: Thalatta.art
    url: https://thalatta.art
  - name: Peridot Homes
    url: https://peridot-homes.com
  - name: Staging Peridot Homes
    url: https://staging.peridot-homes.com
  - name: IPv4 test
    url: 31.220.75.11
    port: 80
    check: "tcp-ping"
    ipv4: true
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: status.thalatta-thalatta.com
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /thalatta
  logoUrl: https://thalatta-thalatta.com/wp-content/themes/thalata-com/assets/logo-dark.svg
  introMessage: This is **real-time** data from Thalatta S.A
  navbar:
    - title: Thalatta-Thalatta  S.A.
      href: /

